buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        implementation 'com.rmtheis:tess-two:9.1.0'
        classpath 'com.android.tools.build:gradle:8.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
